services:
  postgres_db:
    image: postgres:16-alpine
    container_name: car_service_db
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: car_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "8443:8443"
    volumes:
      - ./web:/app
      - /app/node_modules

volumes:
  pgdata: